apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simpleapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/markpanizales/argo-simple-app.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: simpleapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true